Update Spanish translation
getting-things-gnome/gtg pull request #536
Opened 2021-01-06 20:43 UTC by oscfdezdz

2021-01-17 18:15 UTC, diegogangl requested changes
Gracias! No llegue a ver todo y me quedo sin tiempo, pero despues le pego otro vistazo

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
> +msgstr "Organizador de tareas personales y de artículos de la lista TODO"
Me parece que alcanza con "Organizador de tareas personales para GNOME". Ademas la palabra TODO para hispanoparlantes puede ser confusa

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
Me parece que no hace falta "comunes" aca (aunque este en el original)

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
Mismo comentario sobre lista TODO

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
> +msgstr "Eliminar automáticamente las tarea antiguas cerradas"
"las tareas cerradas" creo que quedaria mas corto

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
> +msgstr "Días que esperar antes de quitar una tarea"
Creo que es correcto, pero me suena mas natural "Dias a esperar". No se porque :P

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
> +msgstr "Etiquetas de cambio de lote en las tareas seleccionadas"
"Cambiar etiquetas en tareas seleccionadas" me parece que seria mas corto

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
Habria que definir si los verbos van a ir en infinitivo o como mas abajo para mantener la consistencia. Quizas seria mas facil conjugar este

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
Lo que hace este boton es abrir y cerrar la barra lateral. No se me ocurre que palabra usar para toggle, pero seria como algo que permita abrir y cerrar  >_>

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
"due on" se usaria con una fecha al lado

2021-01-17 18:15 UTC, diegogangl commented on po/es.po
> +msgstr "VALE"
Me parece que seria mas neutro dejar OK aca

2021-01-17 19:08 UTC, oscfdezdz commented on po/es.po
Quizás conmutar sería mejor opción entonces, o alternar

2021-01-17 19:16 UTC, oscfdezdz commented on po/es.po
Entonces sería mejor dejarlo como estaba inicialmente o acortarlo y dejarlo como "Vencimiento para"

2021-01-17 19:28 UTC, oscfdezdz commented
He cambiado las líneas que he marcado como resueltas y alguna más que he visto al repasar la traducción. Las dos pendientes quedan por decidir y si queda alguna más, las cambiaré en el siguiente commit.

2021-01-17 19:56 UTC, oscfdezdz commented on po/es.po
> +msgstr "vencimiento"
Lo he cambiado pensando que lo había traducido yo, ya lo tengo corregido para el próximo commit

2021-01-17 20:46 UTC, oscfdezdz commented
Me acabo de dar cuenta de que el .pot no está actualizado, hay líneas que no están añadidas o no han sido marcadas para traducir y en esta MR tampoco están al haberlo actualizado desde ese. ¿Hay alguna manera de generarlo incluyendo las líneas más recientes? He probado con POedit pero no lo hace de la mejor forma.

2021-01-17 22:33 UTC, diegogangl commented on po/es.po
Si, "vencimiento para" suena bien

2021-01-17 22:35 UTC, diegogangl commented on po/es.po
alternar creo que estaria mejor, despues veremos si cambia esa parte del GUI para ser mas clara tambien :+1:

2021-01-17 22:37 UTC, diegogangl commented
Tendrias que correr `ninja -C .local_build gtg-pot gtg-update-po` para actualizar

Aca esta la guia de como traducir:
https://github.com/getting-things-gnome/gtg/blob/master/docs/contributors/translating.md

2021-01-18 13:16 UTC, oscfdezdz commented
Ya están todas las líneas y cambiadas las que me propusiste. Siento no haberme informado bien sobre como contribuir a las traducciones en primer lugar 😅

2021-01-22 20:54 UTC, diegogangl commented
Buenas, lo probe en el programa en si y me parece que "vencimiento para", quedaria mejor como "vence el" o "vence". "Empieza" tambien quedaria mejor porque a veces tendriamos palabras como "hoy" al lado (y quedaria "empieza el hoy").

Veo que los dias debajo del menu de "Empieza mañana" no estan traducidos, no salen el pot?

2021-01-22 22:21 UTC, oscfdezdz commented
Buenas, he cambiado esas que me has dicho.

Los días que salen debajo de "Empieza mañana" no aparecen en el pot aunque lo actualice, solo aparecen otras traducciones de días con la primera letra en mayúsculas.

En mi caso si que aparecen traducidas, adjunto imagen:
![gtg](https://user-images.githubusercontent.com/42654671/105554446-4ccf4500-5cff-11eb-8682-47dfe65beaed.png)

He pensado que quizás se deba a que tuve que eliminar algunas líneas de `POTFILES.in`, porque como indica la guía puede aparecer errores, y en mi caso ocurría. Pero en ese caso, no debería poder ver las traducciones y como puedes ver en la captura, sí que aparecen.

2021-01-23 19:48 UTC, diegogangl commented
Buenas, bueno lo voy mergeando. Los dias no me salen, pero he notado que en otras traducciones (como `fr_FR`) tampoco salen. Probablemente haya que arreglar algo en ese menu antes de poder hacer las traducciones.

Gracias!

2021-01-23 19:48 UTC, merged