Save task before creating parent
getting-things-gnome/gtg pull request #750
Opened 2022-01-10 22:58 UTC by diegogangl

Saving makes sure the task has the correct title when being added as a
subtask to the new parent. Otherwise the title gets overwritten with the
default title.

fixes #745

2022-01-11 04:29 UTC, nekohayo requested changes
Tested, it works for the case where you create a brand new task and then click "Add Parent", but it doesn't work in the case where you open an existing child task, change its title and immediately click the "Open Parent" button.

2022-01-11 18:30 UTC, diegogangl commented
Force pushed a fix

2022-01-11 23:30 UTC, Neui commented
Looks similar to my fix in the issue, so the title thing works better, but still has the problem that if you type too fast and click add parent fast, then it still won't get applied.

https://user-images.githubusercontent.com/1196130/149037479-65c69e0b-18e4-4558-b19c-b36640f6e9cf.mp4

Of course you have to be quite fast, so it might not be a realistic scenario, but I'd still consider a bug.

2022-01-12 02:44 UTC, nekohayo commented
I can confirm that from a normal user's standpoint, the issue is solved with the revised commit, though "in theory" still exists if you click ultra fast (as in, less than a quarter of a second delay or something like that) which I can't imagine someone encountering unless they're actively _trying_ to trigger the bug.

So if there's a way to guard against that theoretical bug without adding much more code complexity then that's ideal, as it might prevent some other unforeseen issues maybe (race conditions or domino effects, anyone?), otherwise I wouldn't be utterly shocked if the fix solves only the user-visible problem and "hopes" it won't be a real problem beyond that.

2022-01-12 13:09 UTC, diegogangl commented
A potential fix would be using `self.textview.process()` directly. The problem is that it calls light save which has a timer, so you don't get the effects of this fix. The proper solution would be to revisit taskview to use signals, and whether we really need light save (since lxml does everything in a few ms). Then we could call `process()` while disabling the signals, and then call `save()` immediately after.

2022-01-20 21:22 UTC, diegogangl commented
Let's go ahead and merge this for now. I plan on revisiting the textview and the editor in the near future anyways (once we complete the Gtk4 transition at least)

2022-01-20 21:22 UTC, merged