Update NEWS for 0.6
getting-things-gnome/gtg pull request #762
Opened 2022-01-29 22:20 UTC by vansia43

I added in the updates from the Gdoc. I put it in similar categories as was done for the previous releases. I went a little more in-depth than 1 line for some of the new features since I wasn't sure if we were also going to have a blog post. 

The only one that I didn't include was `Fixed several nekobugs [expand]` because I wasn't really sure what that meant. If you want me to add something for that, I can. I also want to make sure `Fixed the bug where every editor window would pop back if GTG wasn’t closed cleanly (ie, shutting down the pc)` was true because there was a comment on the Gdoc questioning it. 

Let me know if you would like any other changes.

2022-01-29 22:49 UTC, Neui commented
I wrote those [] comments.

> Fixed the bug where every editor window would pop back if GTG wasn’t closed cleanly (ie, shutting down the pc)

I thought of https://github.com/getting-things-gnome/gtg/issues/713 so I questioned it. Also I don't remember (and it seems at least I don't find it via the milestone) anoter issue or PR about it.

> Fixed several nekobugs

I wrote [expand] because it isn't really useful. Maybe look at the milestone with author being neko, and check if an entry already exists. I don't think https://github.com/getting-things-gnome/gtg/pull/741 is on it ("Fixed possible crash when trying to create parent task and similar operations when the "Open" tab has not been opened yet").

2022-01-29 23:25 UTC, diegogangl reviewed
lol yeah, no need to include nekobugs. I started writing things of the top of my head, then I had a little more time and started going through the git log and added the actual bugs.

Sorry, forgot a couple bug fixes. Fixed a regression where symbols in tags (like dashes and dots) were not recognized by the task editor. Added support for a  few more. (commit 95db8c6ef31809cb3c09df5f4a9281176f766654).

Also fixed a bug where tags' icon, parent and color were not being removed in the XML file.

Also, fixed a bug when GTG had just started and there were no tasks selected, and the user tried used the "Add Parent" hotkey

> I thought of #713 so I questioned it. Also I don't remember (and it seems at least I don't find it via the milestone) anoter issue or PR about it.

This is super weird. I remember the bug driving me nuts in 0.5, and I can verify it's not in 0.6 since I've been using it for a while. Even killing gtg doesn't trigger it now. I vaguely remember doing something about it, but I can't find the commit.

2022-01-30 16:03 UTC, vansia43 commented on NEWS
> + • New CalDAV backends are available, and the backends dialog is available again.
Ah, that's what I copied from the Gdoc. But I will update. Makes sense :)

2022-01-30 16:13 UTC, vansia43 commented
> This is super weird. I remember the bug driving me nuts in 0.5, and I can verify it's not in 0.6 since I've been using it for a while. Even killing gtg doesn't trigger it now. I vaguely remember doing something about it, but I can't find the commit.

Yea... I can't find anything that backs up that this was fixed. Since there's no real commit or PR to tie it to then, should I take it out? Or, keep it in here since I guess it is technically fixed haha? I'll add in the other ones you talked about as well when I make the other updates below.....


> I don't think #741 is on it ("Fixed possible crash when trying to create parent task and similar operations when the "Open" tab has not been opened yet").

@Neui I have `• Made task expansion more efficient (prevents the maximum recursion depth error).` on here from the Gdoc. I thought this was the same issue, but I can add your text to the bullet as well to expand on it...so something like:

`Made task expansion more efficient (prevents the maximum recursion depth error). This also fixed a possible crash when trying to create a parent task and similar operations when the "Open" tab has not been opened yet.`

Something like that... I will make all of these changes at once when I hear back. Thanks!

2022-01-30 16:24 UTC, Neui commented
> I thought this was the same issue, but I can add your text to the bullet as well to expand on it...so something like:
> 
> `Made task expansion more efficient (prevents the maximum recursion depth error). This also fixed a possible crash when trying to create a parent task and similar operations when the "Open" tab has not been opened yet.`

I somehow missed that line...
IMO "Made task expansion more efficient" is what the PR did (implementation detail), but the crash fix is probably more interesting (directly impacts the usability) so I would have put it first, so something like:

* Fixed possible crash when trying to create parent task and similar operations when the "Open" tab has not been opened yet (maximum recursion depth error)

Not sure if there is a "real" measurable performance improvement for it, so I wouldn't explicitly call it out if we don't have anything to show.

2022-01-30 16:30 UTC, Neui commented on NEWS
> + • Fixed an issue with tasks losing their status during restart.
Refers to #719, except it is a fix for an regression that occurred during the v0.6 development, so technically not a change from v0,5 → v0,6.

2022-01-30 17:47 UTC, nekohayo commented
The existing NEWS file, for previous releases, tried to separate bullet list items by categories according to the various target audiences, i.e. User-visible new features and bugfixes, vs code maintenance, vs contributors' tooling / things that help the project grow, ... could such a split be done here too, if not too much trouble?

2022-01-30 19:00 UTC, nekohayo requested changes

2022-01-30 19:03 UTC, Neui commented on NEWS
> + • The Tag Editor was completely redesigned.
Both. Redesigned visually, made an UI file, and changed the code to use GTK Templates and some other stuff.

2022-01-30 19:18 UTC, Neui commented on NEWS
> + • Made task expansion more efficient (prevents the maximum recursion depth error).
Note that I have written above something about it, and suggested: "Fixed possible crash when trying to create parent task and similar operations when the "Open" tab has not been opened yet (maximum recursion depth error)"

2022-01-30 22:28 UTC, diegogangl commented
> @diegogangl Yea... I can't find anything that backs up that this was fixed. Since there's no real commit or PR to tie it to then, should I take it out? 

We know a few users suffered that bug, I would keep it for all the ones that didn't bother sending a bug report

2022-01-31 14:54 UTC, diegogangl commented
Late-PR merging,  could you add https://github.com/getting-things-gnome/gtg/pull/732 ?
Makes the Defer to tomorrow button adaptive so the window can be resized to smaller widths

2022-01-31 23:44 UTC, vansia43 commented
OK. Everyone's suggestions/changes/additions should be on there.

2022-02-01 22:46 UTC, diegogangl approved these changes

2022-02-03 16:09 UTC, nekohayo approved these changes
Looks good to me too. Fabulous work, thank you so much!

2022-02-03 22:23 UTC, merged

2022-02-03 22:24 UTC, diegogangl commented
Merged, thanks!