Cleanup _parse_only_month_day_for_recurrency
getting-things-gnome/gtg pull request #769
Opened 2022-02-04 00:38 UTC by zeddo123

I tried rewriting the whole function to make more clean and clear.

2022-02-04 22:01 UTC, diegogangl requested changes
Overall it looks good, and it works as well as it did before. Some unit tests might be good, but I'm not sure we should be spending so much time on this. Dateutils can do this already (https://dateutil.readthedocs.io/en/stable/relativedelta.html) and we could probably use it for other things too. 
We should take another look at this date module in the next cycle

2022-02-04 22:45 UTC, zeddo123 commented
> but I'm not sure we should be spending so much time on this. 

Yeah just for now until we rewrite the repeating tasks.

2022-02-06 21:58 UTC, diegogangl approved these changes

2022-02-06 21:58 UTC, merged

2022-02-06 21:58 UTC, diegogangl commented
Thanks!